// Optional development smoke test. Requires Playwright, separate from the zero-dependency app.
import {createRequire} from 'node:module';
import {writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||process.cwd()]}));
const dir=process.env.DAYBRIDGE_EVIDENCE_DIR||'/tmp/daybridge-evidence';await mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.DAYBRIDGE_CHROME?{executablePath:process.env.DAYBRIDGE_CHROME}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.DAYBRIDGE_BASE_URL||'http://127.0.0.1:4173');
await page.getByRole('button',{name:'Rescue tomorrow'}).click();
await page.getByRole('button',{name:'Protect lunch',exact:true}).click();
const preview=await page.evaluate(()=>JSON.parse(localStorage.getItem('daybridge-demo-v1')));
assert.equal(preview.calendarRevision,0);assert.equal(preview.plan.status,'proposed');assert.equal(preview.constraints.lunch,true);
await page.screenshot({path:dir+'/DayBridge_Preview.png',fullPage:true});
await page.getByRole('button',{name:'Apply calendar plan'}).click();
await page.getByLabel('Test one message delivery outage').check();
await page.getByRole('button',{name:'Approve handoff message'}).click();
let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('daybridge-demo-v1')));
assert.equal(state.outbox.length,0);assert.ok(state.jobs.some(j=>j.status==='failed'));const rev=state.calendarRevision;
await page.getByRole('button',{name:'Retry failed actions',exact:true}).click();
state=await page.evaluate(()=>JSON.parse(localStorage.getItem('daybridge-demo-v1')));
assert.equal(state.outbox.length,1);assert.equal(state.calendarRevision,rev);assert.equal(state.tasks[0].status,'todo');
await page.reload();
const restored=await page.evaluate(()=>JSON.parse(localStorage.getItem('daybridge-demo-v1')));
assert.equal(restored.outbox.length,1);assert.equal(restored.constraints.lunch,true);
await page.screenshot({path:dir+'/DayBridge_Completed.png',fullPage:true});
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export JSON'}).click();const download=await downloadPromise;await download.saveAs(dir+'/DayBridge_Execution_Receipts.json');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:dir+'/DayBridge_Mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
await page.getByRole('button',{name:'Reset demo',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'Apply calendar plan'}).isDisabled(),true);
assert.equal(errors.length,0);
await writeFile(dir+'/Browser_Check_Result.json',JSON.stringify({passed:true,checks:['preview makes no writes','follow-up preserves context','calendar approval executes','separate message approval','adapter outage recorded','retry does not repeat calendar changes','state survives reload','JSON export contains real local receipts','390px mobile has no horizontal overflow','reset clears state','no browser runtime errors'],runtimeErrors:errors,completedAt:new Date().toISOString(),scope:'local synthetic simulation only'},null,2));
await browser.close();console.log('Browser checks passed: 11 checks, desktop and 390px mobile; no runtime errors.');
