// Reproducible recording of the actual functioning UI; no fabricated provider output.
import {createRequire} from 'node:module';
import {mkdir,writeFile,rename} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||process.cwd()]}));
const dir=process.env.DAYBRIDGE_EVIDENCE_DIR||'/tmp/daybridge-evidence';await mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.DAYBRIDGE_CHROME?{executablePath:process.env.DAYBRIDGE_CHROME}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1100},recordVideo:{dir,size:{width:1440,height:1100}}});
const page=await context.newPage();
const notes=[];const started=Date.now();
function note(text){notes.push({seconds:(Date.now()-started)/1000,text});console.log(text);}
const hold=ms=>new Promise(r=>setTimeout(r,ms));
await page.goto(process.env.DAYBRIDGE_BASE_URL||'http://127.0.0.1:4173');
note('DayBridge: an Alexa+ experience simulation. Synthetic data; no live Alexa or LLM.');await hold(9000);
await page.getByRole('button',{name:'Rescue tomorrow'}).click();
note('One goal becomes a preview across calendar, tasks and a family handoff. The calendar is unchanged.');await hold(15000);
await page.getByRole('button',{name:'Protect lunch',exact:true}).click();
note('A follow-up preserves context and protects lunch. The revised plan still needs approval.');await hold(15000);
await page.getByRole('button',{name:'Apply calendar plan'}).click();
note('Calendar changes execute locally. The handoff message remains unsent and requires separate approval.');await hold(16000);
await page.getByLabel('Test one message delivery outage').check();await page.getByRole('button',{name:'Approve handoff message'}).click();
let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('daybridge-demo-v1')));const rev=state.calendarRevision;
assert.equal(state.outbox.length,0);assert.ok(state.jobs.some(j=>j.status==='failed'));
note('An injected local-adapter outage prevents delivery. Completed calendar actions remain completed.');await hold(15000);
await page.getByRole('button',{name:'Retry failed actions',exact:true}).click();
state=await page.evaluate(()=>JSON.parse(localStorage.getItem('daybridge-demo-v1')));assert.equal(state.outbox.length,1);assert.equal(state.calendarRevision,rev);
note('Retry runs only the failed approved message. One local delivery; no duplicated calendar writes.');await hold(15000);
await page.getByRole('heading',{name:'Action receipts',exact:true}).scrollIntoViewIfNeeded();
note('Each receipt records an actual local outcome. These are simulation receipts, not external delivery proof.');await hold(12000);
const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Export JSON'}).click();await (await dl).saveAs(dir+'/DayBridge_Demo_Receipts.json');
await page.reload();await page.getByRole('heading',{name:'Tomorrow, reconciled.',exact:true}).scrollIntoViewIfNeeded();
state=await page.evaluate(()=>JSON.parse(localStorage.getItem('daybridge-demo-v1')));assert.equal(state.outbox.length,1);assert.equal(state.tasks[0].status,'todo');
note('Context survives refresh. The report is scheduled, still unfinished. No real accounts or messages.');await hold(14000);
const end=(Date.now()-started)/1000;const video=page.video();await context.close();const videoPath=await video.path();await rename(videoPath,dir+'/DayBridge_Actual_Demo.webm');
const time=n=>{const ms=Math.floor(n*1000);return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`;};
await writeFile(dir+'/DayBridge_Demo_Captions.srt',notes.map((n,i)=>`${i+1}\n${time(n.seconds)} --> ${time(notes[i+1]?.seconds??end)}\n${n.text}\n`).join('\n'));
await writeFile(dir+'/DayBridge_Recording_Result.json',JSON.stringify({scope:'actual UI footage of local synthetic simulation',completedAt:new Date().toISOString(),durationSeconds:end,outboxCount:state.outbox.length,calendarRevision:state.calendarRevision,reportStatus:state.tasks[0].status,check:'outage, retry, no duplicate writes and persistence assertions passed',notes},null,2));
await browser.close();console.log(`Recorded ${end.toFixed(1)} seconds of functioning UI.`);
